## Get directory to run on
$dir = Read-Host -Prompt "Please input start dir where wav files are loaded"
while(!(Test-Path $dir)){
    $dir = Read-Host -Prompt "Invalid input, try again"
}
## Main paths
$FXwrapperPath = "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Tools\Audio\FaceFXWrapper"
$FonixData = "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Tools\Audio\FonixData.cdf"
$FFmpeg = "C:\Program Files (x86)\Steam\SteamApps\common\Skyrim Special Edition\Tools\Audio\ffmpeg.exe"

$files = Get-ChildItem $dir

##Clean up
Remove-Item -Path $dir -Recurse -Include *.json #Json files by VAsynth
Remove-Item -Path $dir -Recurse -Include *.wav.reapeaks ##Files generated by Reaper (If used for fine tuning)

##Clean up old _32bit.wav files
$32bitWavfolder = "$dir\Raw 32bit WAVs\"
if(Test-Path $32bitWavfolder)
{
    Remove-Item $32bitWavfolder -Force
}
MKDIR -Path "$dir\Raw 32bit WAVs\"

foreach ($file in $files) {
    ##Makes sure its not a old 32 bit file
    if (($file.Extension -eq ".wav") -and !($file.Name -like "*_32bit*")) {
        write-host "On file $file"
        ##Re-name file
        $oldwavfile = $32bitWavfolder+[io.path]::GetFileNameWithoutExtension($file.Name)+"_32bit.wav"
        Copy-Item -Path $file.FullName -Destination $oldwavfile -Force #Copy renamed old wav to folder
        Remove-Item -Path $file.FullName -Force #Delete the old version of Wav

        ##Convert to 16bit mono
        $filename = $file.FullName
        $ffmpegargs =  '-i',  "`"$oldwavfile`"", '-acodec', 'pcm_s16le', '-ar', '44100', "`"$filename`""
        & $ffmpeg  $ffmpegargs
        
        ##Extract Dialouge from title using VA synth style
        $dialouge = $file.Name
        $dialouge = $dialouge.SubString($dialouge.LastIndexOf("_")+1, ($dialouge.IndexOf(".")-1) - $dialouge.LastIndexOf("_"))
        Write-host "Dialogue found: $dialouge"

        #Quotes needed for args! Do not remove!!!!!!!!
        $lipout = $file.DirectoryName+"\"+[io.path]::GetFileNameWithoutExtension(($file).Name)+".lip"
        $argus =  "`"Skyrim`"", "`"USEnglish`"", "`"$FonixData`"", "`"$filename`"", "`"$filename`"", "`"$lipout`"", "`"$dialouge`""

        ##Run LIP gen
        &$FXwrapperPath $argus
    }
}